### ISSUE TITLE
The SCSS templates are missing variables for font color

### ISSUE THREAD

**Issue by TikiTDO** [silevis/reactgrid#183]
**Describe the bug**

There are no variables in the SCSS templates that control the color of the text. 

**Current behavior**

The text is always the inherited color

**Expected behavior**

There should be SCSS variables that I can set to configure the color of text used by the grid. Currently I work around it as below, but explicit variables for these things would be nice.

```scss
.grid-dark {
  // Dark mode colors
  $primary-color: #ff5a5a !default;
  $bg-color: #111111 !default;
  $sticky-bg-color: #111111 !default;
  $shadow-color: #ffffff !default;
  $resize-line-color: #25a1d9 !default;
  $resize-hint-bg-color: $resize-line-color !default;
  $resize-handle-gb-color: $primary-color !default;
  $cell-border-color: #ffffff !default;
  $cell-editor-bg-color: #111111 !default;
  $cell-editor-border-color: $primary-color !default;
  $fillhandle-action-border-color: #ffffff !default;
  $partial-area-gb-color: $primary-color !default;
  $partial-area-border-color: $primary-color !default;
  $checkbox-checked: $primary-color !default;
  $checkbox-unchecked: #333333 !default;
  $checkbox-hover: #555555 !default;
  $checkbox-mark: #000000 !default;
  $dropdown-focused-item-bg-color: darken(
    $color: $primary-color,
    $amount: 35,
  ) !default;
  $dropdown-menu-bg-color: #111111 !default;

  @import "@silevis/reactgrid/styles.scss";

  .rg-header-cell {
    background-color: #1b4b22 !important;
  }

  color: #eee;

  input {
    color: #eee;
  }
}
```
